#! /bin/sh

set -e

#DEBHELPER#

case "$1" in
    remove|purge)
        for p in $(pyversions -i); do
            $p -c 'from twisted.plugin import IPlugin, getPlugins; list(getPlugins(IPlugin))' >/dev/null 2>&1 || true
        done
        ;;
esac

if [ "$1" = "purge" ]; then
    deluser --system qcss3 || true
    delgroup --system qcss3 || true
    rm -rf /var/run/qcss3
    rm -rf /var/log/qcss3
fi

exit 0
